version: "2"
checks:
  method-lines:
    config:
      threshold: 28
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
- "config/"
- "dist/"
- "**/node_modules/"
- "**/__tests__/"
- "client/views/Generator/index.jsx"
