version: "2"
checks:
  method-lines:
    config:
      threshold: 28
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
- "config/"
- "dist/"
- "**/node_modules/"
- "**/spec/"
- "**/test/"
- "**/tests/"
